#!/usr/bin/env bash

MTPROTO_HOST_DIR=$(pwd)

MTPROTO_HOST_CONFIG_PATH="${MTPROTO_HOST_CONFIG_PATH:-config.py}"
# Add prefix if relative
if [ ! "${MTPROTO_HOST_CONFIG_PATH:0:1}" = "/" ]; then
  MTPROTO_HOST_CONFIG_PATH=${MTPROTO_HOST_DIR}/${MTPROTO_HOST_CONFIG_PATH}
fi

MTPROTO_HOST_CONFIG_FILENAME="$(basename "${MTPROTO_HOST_CONFIG_PATH}")"
MTPROTO_DOCKER_DIR="/home/tgproxy/"

IFS='' read -r -d '' MTPROTO_COMAND <<"EOF"
  MTPROTO_HOST_DIR=${MTPROTO_HOST_DIR} \
  MTPROTO_HOST_CONFIG_PATH=${MTPROTO_HOST_CONFIG_PATH} \
  MTPROTO_HOST_CONFIG_FILENAME=${MTPROTO_HOST_CONFIG_FILENAME} \
  MTPROTO_DOCKER_DIR=${MTPROTO_DOCKER_DIR} \
  docker-compose run -d \
    mtprotoproxy \
    python3 mtprotoproxy.py ${MTPROTO_DOCKER_DIR}/${MTPROTO_HOST_CONFIG_FILENAME}
EOF

eval "$MTPROTO_COMAND"
